[project]
name = 'Meeting-Multiplication-Microservice-Mesh'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.action-item-entropy-generator]
path = 'contracts/action-item-entropy-generator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.calendar-tetris-optimization-engine]
path = 'contracts/calendar-tetris-optimization-engine.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
